additional column
babakw/test-repo pull request #4
Opened 2021-02-09 07:57 UTC by babakw

please do review

2021-02-09 08:00 UTC, wojtekbabak commented on create_table3
> +sdasads decial(38,10)
typo in data type

2021-02-09 08:01 UTC, wojtekbabak requested changes
please fix this

2021-02-09 08:01 UTC, wojtekbabak commented on create_table3
>  create multiset table3(
fsdfsdfsd

2021-02-09 08:02 UTC, babakw commented on create_table3
> +sdasads decial(38,10)
fixed

2021-02-09 08:03 UTC, babakw commented on create_table3
>  create multiset table3(
ok done
```suggestion
create multiset table3(fgdf
```

2021-02-09 08:05 UTC, wojtekbabak reviewed
everything looks fine

2021-02-09 08:06 UTC, wojtekbabak approved these changes

2021-02-10 11:35 UTC, closed without merging

2021-02-10 11:35 UTC, babakw commented
test